/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.example.kotlindsl

fun main() {
    val pen = Pen()
    val result = pen.up() N 4 E 8 S 4 W 8
    result.down()
}
